swagger: "2.0"
info:
  version: 1.0.0
  title: express-microservice
  description: Express Microservice Starter
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        description: The example name

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: body
          in: body
          description: number of items to skip
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not available
  /shop/products:
      get:
        tags:
          - Products
        description: Fetch all examples
        responses:
          200:
            description: Returns all examples
  /shop/products/{id}:
      get:
        tags:
          - Products
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available
  /shop/productOptions:
      get:
        tags:
          - Products
        description: Fetch all examples
        responses:
          200:
            description: Returns all examples
  /shop/productOptions/{id}:
      get:
        tags:
          - Products
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available
  /shop/prices:
      get:
        tags:
          - Products
        description: Fetch all examples
        responses:
          200:
            description: Returns all examples
  /shop/prices/{id}:
      get:
        tags:
          - Products
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available
  /shop/inventory:
      get:
        tags:
          - Products
        description: Fetch all examples
        responses:
          200:
            description: Returns all examples
  /shop/inventory/{id}:
      get:
        tags:
          - Products
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available
  /shop/priceByOptionId/{id}:
      get:
        tags:
          - Products
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available            
  /starwars/people/{id}:
      get:
        tags:
          - Starwars
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the entity to retrieve
            type: integer
        responses:
          200:
            description: Return the example with the specified id
          404:
            description: Example not available            
  /shop/invokePreFetchCheckAvailability/{id}:
      post:
        tags:
          - Shop/Unified
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: addressInfo
            in: body
            required: true
            description: The id of the entity to retrieve            
            schema :
              type: object
              properties :
                zipCode :
                  type : string
                addressLine :
                  type : string
                mode :
                  type : string
        responses:
          200:
            description: Return the availability status
            schema:
              type : object
              properties :
                statusCode :
                  type : integer
                statusName :
                  type : string
          404:
            description: Service is not available
  /users/login:
      post:
        tags:
          - Users
        parameters:
          - name: accessInfo
            in: body
            required: true
            description: The id of the entity to retrieve
            schema:
              type : object
              properties:
                username :
                  type : string
                password :
                  type : string
        responses:
          200:
            description: Return true/false
          404:
            description: Users not available
  /products:
      get:
        tags:
          - Products        
        responses:
          200:
            description: Return products
          404:
            description: Products not available
      post:
        tags:
          - Products
        parameters:
          - name: product
            in: body
            required: true
            description: The id of the entity to retrieve
            schema:
              type : object
              properties:
                productName :
                  type : string
                pack :
                  type : string
                mrp :
                  type : integer
                rate :
                  type : integer
                cost :
                  type : integer
                vat :
                  type : integer
                mfgr :
                  type : string
                minStock :
                  type : integer                                                                                                
                hsnCode :
                  type : string                  
        responses:
          200:
            description: Return products
          404:
            description: Products not available
